# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KoykW8tGOc58qicy8P1RhOoxQ4Wb5aTQ

# Amazon Product Review Summarization App
## NLP + Transformer-Based Review Analysis
"""

# =====================================
# Amazon Review Summarization App
# =====================================

import gradio as gr

from transformers import pipeline

# -------------------------------------
# Load Transformer Pipeline
# -------------------------------------

generator = pipeline(
    task="text-generation",
    model="gpt2"
)

# -------------------------------------
# Extractive Summary
# -------------------------------------

def extractive_summary(text):

    # Split reviews using pipe separator
    reviews = text.split("|")

    # Simple extractive strategy:
    # return first two reviews combined
    summary = " ".join(reviews[:2])

    return summary.strip()


# -------------------------------------
# Abstractive Summary
# -------------------------------------

def abstractive_summary(text):
  # Prompt engineering for transformer generation
    prompt = f"""
    Summarize these customer reviews:

    {text}

    Summary:
    """

    result = generator(
        prompt,
        max_new_tokens=60,
        do_sample=False
    )

    return result[0]["generated_text"]


# -------------------------------------
# Main App Function
# -------------------------------------

def summarize_reviews(text, method):

    if method == "Extractive":
        return extractive_summary(text)

    elif method == "Abstractive":
        return abstractive_summary(text)

    else:
        return "Invalid summarization method."


# -------------------------------------
# Gradio Interface
# -------------------------------------

demo = gr.Interface(
    fn=summarize_reviews,


    inputs=[
        gr.Textbox(
            lines=10,
            placeholder="Enter multiple reviews separated by |"
        ),

        gr.Radio(
            choices=[
                "Extractive",
                "Abstractive"
            ],
            value="Extractive",
            label="Summarization Method"
        )
    ],

    outputs=gr.Textbox(label="Generated Summary"),


    examples=[
        [
            "Great battery life | Fast charging | Very durable cable",
            "Extractive"
        ],

        [
            "Amazing sound quality | Battery lasts long | Comfortable headphones",
            "Abstractive"
        ]
    ],


    title="Amazon Review Summarization App",

    description="""
    Enter multiple customer reviews separated by |
    and generate either extractive or abstractive summaries.
    """
)

# -------------------------------------
# Launch App
# -------------------------------------

demo.launch()

"""## Application Insights

The Gradio application demonstrates how transformer-based NLP systems can be integrated into lightweight interactive AI tools for real world ecommerce use cases.

Users can input multiple customer reviews and instantly generate either extractive or abstractive summaries. This type of workflow could help businesses automate large scale customer feedback analysis and improve decision-making efficiency.
"""